import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/main/Footer";
import { ThemeProvider } from "next-themes";
import { NavbarDemo } from "@/components/main/NavbarDemo";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeAstera | Web Development Services ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} bg-[rgb(3,0,13)] font-geistSans`}>
        
            <NavbarDemo />

            <ThemeProvider attribute="class" defaultTheme="dark">
              {children}
            </ThemeProvider>
            <Footer />
       
      </body>
    </html>
  );
}
